spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://10.211.55.15:8084
  zipkin:
    base-url: http://10.211.55.15:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.211.55.15:8761/eureka/,http://10.211.55.15:8861/eureka/,http://10.211.55.15:8961/eureka/
zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info