spring:
  application:
    name: itoken-service-upload
  boot:
    admin:
      client:
        url: http://10.211.55.15:8084
  zipkin:
    base-url: http://10.211.55.15:9411

server:
  port: 8506
fastdfs.base.url: http://10.211.55.8:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 10.211.55.8:22122


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.211.55.15:8761/eureka/,http://10.211.55.15:8861/eureka/,http://10.211.55.15:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info