spring:
  application:
    name: itoken-web-admin
  boot:
    admin:
      client:
        url: http://10.211.55.15:8084
  zipkin:
    base-url: http://10.211.55.15:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8601
feign:
  hystrix:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.211.55.15:8761/eureka/,http://10.211.55.15:8861/eureka/,http://10.211.55.15:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info